---
kind: Deployment
apiVersion: apps/v1beta2
metadata:
  name: powersource-app
  namespace: mucon
spec:
  replicas: 2
  selector:
    matchLabels:
      service: powersource-service
  template:
    metadata:
      name: powersource-app
      labels:
        name: powersource-app
        app: powersource-app
        service: powersource-service
    spec:
      containers:
      - name: jaeger-agent
        image: jaegertracing/jaeger-agent
        ports:
        - containerPort: 5775
          protocol: UDP
        - containerPort: 5778
        - containerPort: 6831
          protocol: UDP
        - containerPort: 6832
          protocol: UDP
        command:
        - "/go/bin/agent-linux"
        - "--collector.host-port=jaeger-collector:14267"
        resources:
          limits:
            cpu: 0.05
            memory: 128Mi
          requests:
            cpu: 0.05
            memory: 128Mi
      - name: powersource-app
        imagePullPolicy: Never
        image: mucon/powersource:v0.1.0
        ports:
        - name: http
          containerPort: 6061
          protocol: TCP
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: "/live"
            port: 6061
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: "/health"
            port: 6061
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 10
        resources:
          limits:
            cpu: 0.1
            memory: 256Mi
          requests:
            cpu: 0.1
            memory: 256Mi
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1