---
kind: Deployment
apiVersion: apps/v1beta2
metadata:
  name: superpower-app
  namespace: mucon
spec:
  replicas: 2
  selector:
    matchLabels:
      service: superpower-service
  template:
    metadata:
      name: superpower-app
      labels:
        name: superpower-app
        app: superpower-app
        service: superpower-service
    spec:
      containers:
      - name: jaeger-agent
        image: jaegertracing/jaeger-agent
        ports:
        - containerPort: 5775
          protocol: UDP
        - containerPort: 5778
        - containerPort: 6831
          protocol: UDP
        - containerPort: 6832
          protocol: UDP
        command:
        - "/go/bin/agent-linux"
        - "--collector.host-port=jaeger-collector:14267"
        resources:
          limits:
            cpu: 0.05
            memory: 128Mi
          requests:
            cpu: 0.05
            memory: 128Mi
      - name: superpower-app
        ports:
        - name: http
          containerPort: 6060
          protocol: TCP
        imagePullPolicy: Never
        image: mucon/superpower:v0.1.0
        env:
          - name: POWERSOURCE_URL
            value: http://powersource-service:8080
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: "/live"
            port: 6060
          initialDelaySeconds: 10
          periodSeconds: 20
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: "/health"
            port: 6060
          initialDelaySeconds: 10
          periodSeconds: 20
          timeoutSeconds: 10
        resources:
          limits:
            cpu: 0.2
            memory: 256Mi
          requests:
            cpu: 0.1
            memory: 256Mi
      - name: superpower-static-app
        ports:
        - name: static
          containerPort: 80
          protocol: TCP
        imagePullPolicy: Never
        image: mucon/superpower-static:v0.1.0
        resources:
          limits:
            cpu: 0.2
            memory: 128Mi
          requests:
            cpu: 0.05
            memory: 128Mi
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1