---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-query
  namespace: mucon
  labels:
    app: jaeger
    jaeger-infra: jaeger-service
spec:
  ports:
    - name: query-http
      port: 80
      protocol: TCP
      targetPort: 16686
      nodePort: 30141
  selector:
    jaeger-infra: jaeger-pod
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector
  namespace: mucon
  labels:
    app: jaeger
    jaeger-infra: collector-service
spec:
  ports:
  - name: jaeger-collector-tchannel
    port: 14267
    protocol: TCP
    targetPort: 14267
  - name: jaeger-collector-http
    port: 14268
    protocol: TCP
    targetPort: 14268
  - name: jaeger-collector-zipkin
    port: 9411
    protocol: TCP
    targetPort: 9411
  selector:
    jaeger-infra: jaeger-pod
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-agent
  namespace: mucon
  labels:
    app: jaeger
    jaeger-infra: agent-service
spec:
  ports:
  - name: agent-zipkin-thrift
    port: 5775
    protocol: UDP
    targetPort: 5775
  - name: agent-compact
    port: 6831
    protocol: UDP
    targetPort: 6831
  - name: agent-binary
    port: 6832
    protocol: UDP
    targetPort: 6832
  - name: agent-configs
    port: 5778
    protocol: TCP
    targetPort: 5778
  selector:
    jaeger-infra: jaeger-pod
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: zipkin
  namespace: mucon
  labels:
    app: jaeger
    jaeger-infra: zipkin-service
spec:
  ports:
  - name: jaeger-collector-zipkin
    port: 9411
    protocol: TCP
    targetPort: 9411
  clusterIP: None
  selector:
    jaeger-infra: jaeger-pod
