---
kind: Service
apiVersion: v1
metadata:
  name: prometheus-service
  namespace: mucon
spec:
  type: NodePort
  selector:
    app: prometheus-app
  ports:
  - name: ui
    protocol: TCP
    port: 9090
    targetPort: 9090
    nodePort: 30142