---
kind: Service
apiVersion: v1
metadata:
  name: superpower-service
  namespace: mucon
  labels:
    service: superpower-service
spec:
  type: NodePort
  ports:
  - protocol: TCP
    name: http
    port: 8080
    targetPort: 6060
    nodePort: 30241
  - protocol: TCP
    name: static
    port: 8081
    targetPort: 80
    nodePort: 30242
  selector:
    service: superpower-service
